account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from account import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('edit/', views.EditProfileView.as_view(), name='profile_edit'),
    path('edit/<company_name>/<employee_num>/', views.EditUserByAdminView.as_view(), name='user_edit_by_admin'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('<company_name>/<employee_num>/', views.ProfileDetailView.as_view(), name='profile_detail'),
]

actudoc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('', include('document.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

document/urls.py
from django.urls import path

from document import views

urlpatterns = [
    path('', views.MainView.as_view(), name="main"),
    path('search/', views.MainView.as_view(), name="search"),
    path('manage/', views.ManageView.as_view(), name="manage"),

    path('product/add/', views.AddProductView.as_view(), name="add_product"),
    path('product/edit/<company_name>/<company_product_id>', views.EditProductView.as_view(), name="edit_product"),
    path('product/delete/<company_name>/<company_product_id>', views.DeleteProductView.as_view(), name="delete_product"),

    path('category/add/', views.AddCategoryView.as_view(), name="add_category"),
    path('category/edit/<company_name>/<company_category_id>', views.EditCategoryView.as_view(), name="edit_category"),
    path('category/delete/<company_name>/<company_category_id>', views.DeleteCategoryView.as_view(), name="delete_category"),

    path('document/add/', views.AddDocumentView.as_view(), name="add_document"),
    path('document/edit/<company_name>/<company_document_id>', views.EditDocumentView.as_view(), name="edit_document"),
    path('document/delete/<company_name>/<company_document_id>', views.DeleteDocumentView.as_view(), name="delete_document"),
    path('document/<company_name>/<company_document_id>', views.DocumentDetailView.as_view(), name="document_detail"),
    path('download/<company_name>/<company_document_id>', views.DownloadDocumentView.as_view(), name="download"),
]

document/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models


def validate_file_extension(value):
    if value.file.content_type != "application/pdf":
        raise ValidationError(u"Only PDF files can be uploaded.")


class Company(models.Model):
    name = models.CharField(max_length=32, unique=True)
    full_name = models.CharField(max_length=100)
    code = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        indexes = [models.Index(fields=["name", ])]


class Product(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    company_product_id = models.PositiveIntegerField()
    name = models.CharField(max_length=60, verbose_name="name of insurance product",
                            help_text="E.g. Term Life Insurance")
    model = models.CharField(max_length=20, verbose_name="cash flow model", help_text="E.g. TERM02")

    def __str__(self):
        return f"{self.name} ({self.model})"

    def delete(self, *args, **kwargs):
        documents = self.document_set.all()
        files = [document.file for document in documents]
        for file in files:
            file.delete()
        super().delete(*args, **kwargs)

    def number_of_documents(self):
        return self.document_set.count()

    class Meta:
        indexes = [models.Index(fields=["company", "company_product_id"])]
        ordering = ["id"]
        unique_together = ("company_product_id", "company")


class Category(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    company_category_id = models.PositiveIntegerField()
    name = models.CharField(max_length=100, help_text="E.g. Terms and conditions or Technical description")

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        documents = self.document_set.all()
        files = [document.file for document in documents]
        for file in files:
            file.delete()
        super().delete(*args, **kwargs)

    def number_of_documents(self):
        return self.document_set.count()

    class Meta:
        indexes = [models.Index(fields=["company", "company_category_id"])]
        ordering = ["id"]
        unique_together = ("company_category_id", "company")


def document_path(instance, filename):
    return f"{instance.company.name}/{instance.company_document_id}/{filename}"


class Document(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    company_document_id = models.PositiveIntegerField()
    product = models.ManyToManyField(Product, verbose_name="insurance product")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="document category")
    validity_start = models.DateField(verbose_name="valid from")
    file = models.FileField(upload_to=document_path, validators=[validate_file_extension])
    title = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="create_user")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file.name

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def slug(self):
        return f"{self.company.name}-{self.company_document_id}"

    class Meta:
        indexes = [models.Index(fields=["company", "company_document_id"])]
        ordering = ["-id"]
        unique_together = ("company", "category", "validity_start")


class History(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    element = models.CharField(max_length=100)
    changed_from = models.CharField(max_length=100)
    changed_to = models.CharField(max_length=100)
    changed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="change_user")
    changed_at = models.DateTimeField(auto_now_add=True)

document/views.py
import os
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View

from document import models
from document import forms
from document.utils import utils


class MainView(LoginRequiredMixin, View):
    """
    Home page of the application.

    Shows ten newest documents in reverse-chronological order of company's documents.
    Allows searching documents using a phrase.

    Access company: filtering of objects based on request user's company
    Access roles: all
    """
    def get(self, request):
        company = request.user.profile.company
        documents = models.Document.objects.filter(company=company)

        # User can search documents with a phrase
        phrase = request.GET.get("phrase")
        if phrase:
            documents = utils.search(phrase, company)

        # User can search documents by product
        company_product_id = request.GET.get("product")
        product = None
        if company_product_id:
            product = get_object_or_404(models.Product, company=company, company_product_id=company_product_id)
            documents = documents.filter(product=product)

        # User can search documents by category
        company_category_id = request.GET.get("category")
        category = None
        if company_category_id:
            category = get_object_or_404(models.Category, company=company, company_category_id=company_category_id)
            documents = documents.filter(category=category)

        # Documents are split by pages
        paginator = Paginator(documents, 16)
        page = request.GET.get("page")

        try:
            documents = paginator.page(page)
        except PageNotAnInteger:
            documents = paginator.page(1)
        except EmptyPage:
            documents = paginator.page(paginator.num_pages)

        ctx = {
            "page": page,
            "documents": documents,
            "phrase": phrase,
            "product": product,
            "category": category,
        }
        return render(request, "document/main.html", ctx)


class ManageView(LoginRequiredMixin, View):
    """
    Manage products and categories of the company. Add, edit or delete objects.

    Access company: filtering of objects
    Access role: all can access but only contributors and admins have active links to edit/delete
    """
    def get(self, request):
        company = self.request.user.profile.company
        categories = models.Category.objects.filter(company=company)
        products = models.Product.objects.filter(company=company)
        return render(request, "document/manage.html", {"categories": categories, "products": products})


class AddProductView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Form to add a new product.

    Products have internal ids within company (company_product_id).

    Access company: posted form will take company info from user
    Access roles: contributors and admins (test_func)
    """
    def test_func(self):
        return utils.user_is_contributor_or_admin(self.request)

    def get(self, request):
        form = forms.ProductForm
        return render(request, "document/product_form.html", {"form": form})

    def post(self, request):
        form = forms.ProductForm(request.POST)
        if form.is_valid():
            company = request.user.profile.company
            try:
                latest_product = models.Product.objects.filter(company=company).latest("company_product_id")
                company_product_id = latest_product.company_product_id + 1
            except models.Product.DoesNotExist:
                company_product_id = 1

            name = form.cleaned_data["name"]
            model = form.cleaned_data["model"]
            models.Product.objects.create(
                company=company,
                company_product_id=company_product_id,
                name=name,
                model=model,
            )
            messages.success(request, "Insurance product added!")
            return redirect(reverse_lazy("manage"))
        else:
            return render(request, "document/product_form.html", {"form": form})


class EditProductView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, View):
    """
    Form to edit an existing product.

    Access company: url + logged in user (get + post)
    Access roles: contributors and admins (test_func)
    """
    def test_func(self):
        return utils.user_is_contributor_or_admin(self.request)

    def instance(self, company_name, company_product_id):
        company = get_object_or_404(models.Company, name=company_name)
        product = get_object_or_404(models.Product, company=company, company_product_id=company_product_id)
        return product

    def get(self, request, company_name, company_product_id):
        if not utils.user_is_employee(request, company_name):
            raise PermissionDenied

        product = self.instance(company_name, company_product_id)
        form = forms.ProductForm(instance=product)
        return render(request, "document/product_update_form.html", {"form": form})

    def post(self, request, company_name, company_product_id):
        if not utils.user_is_employee(request, company_name):
            raise PermissionDenied

        product = self.instance(company_name, company_product_id)
        form = forms.ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, "Insurance product updated!")
            return redirect(reverse_lazy("manage"))
        else:
            return render(request, "document/product_update_form.html", {"form": form})


class DeleteProductView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Delete a product.

    Access company: url + logged in user (get + post)
    Access roles: contributors and admins (test_func)
    """
    def test_func(self):
        return utils.user_is_contributor_or_admin(self.request)

    def instance(self, company_name, company_product_id):
        company = get_object_or_404(models.Company, name=company_name)
        product = get_object_or_404(models.Product, company=company, company_product_id=company_product_id)
        return product

    def get(self, request, company_name, company_product_id):
        if not utils.user_is_employee(request, company_name):
            raise PermissionDenied

        product = self.instance(company_name, company_product_id)
        return render(request, "document/product_confirm_delete.html", {"product": product})

    def post(self, request, company_name, company_product_id):
        if not utils.user_is_employee(request, company_name):
            raise PermissionDenied

        product = self.instance(company_name, company_product_id)
        product.delete()
        messages.success(request, "Insurance product deleted!")
        return redirect(reverse_lazy("manage"))


class AddCategoryView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Form to add a new category.

    Access company: posted form will take company info from request user
    Access roles: contributors and admins (test_func)
    """
    def test_func(self):
        return utils.user_is_contributor_or_admin(self.request)

    def get(self, request):
        form = forms.CategoryForm
        return render(request, "document/category_form.html", {"form": form})

    def post(self, request):
        form = forms.CategoryForm(request.POST)
        if form.is_valid():
            company = request.user.profile.company

            try:
                latest_category = models.Category.objects.filter(company=company).latest("company_category_id")
                company_category_id = latest_category.company_category_id + 1
            except models.Category.DoesNotExist:
                company_category_id = 1

            name = form.cleaned_data["name"]
            models.Category.objects.create(
                company=company,
                company_category_id=company_category_id,
                name=name,
            )
            messages.success(request, "Document category added!")
            return redirect(reverse_lazy("manage"))
        else:
            return render(request, "document/category_form.html", {"form": form})


class EditCategoryView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Form to edit an existing category.

    Access company: url + logged in user (get + post)
    Access roles: contributors and admins (test_func)
    """
    def test_func(self):
        return utils.user_is_contributor_or_admin(self.request)

    def instance(self, company_name, company_category_id):
        company = get_object_or_404(models.Company, name=company_name)
        category = get_object_or_404(models.Category, company=company, company_category_id=company_category_id)
        return category

    def get(self, request, company_name, company_category_id):
        if not utils.user_is_employee(request, company_name):
            raise PermissionDenied

        category = self.instance(company_name, company_category_id)
        form = forms.CategoryForm(instance=category)
        return render(request, "document/category_update_form.html", {"form": form})

    def post(self, request, company_name, company_category_id):
        if not utils.user_is_employee(request, company_name):
            raise PermissionDenied

        category = self.instance(company_name, company_category_id)

document/templates/document/category_confirm_delete.html
{% extends "base.html" %}
{% block content %}

    <h3>Delete document category</h3>
    <div class="brick">
        <form method="post">
            {% csrf_token %}

            {% if category.number_of_documents > 0 %}
                <p style="color: rgba(220, 53, 69, 1); font-weight: bold;">DANGER!</p>
                <p>If you delete this document category, you will also delete
                    <strong>{{ category.number_of_documents }}</strong> documents in this category!</p>
            {% endif %}

            <p>Do you really want to delete the document category <strong>{{ category }}</strong>?</p>

            <div class="vertical-center">
                <button type="submit" class="button red-button">Delete document category</button>
            </div>
        </form>
    </div>

{% endblock %}

document/templates/document/category_form.html
{% extends "base.html" %}
{% block content %}

    <h3>Add document category</h3>
    <div class="brick">
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="vertical-center">
                <button type="submit" class="button green-button">Add document category</button>
            </div>
        </form>
    </div>

{% endblock %}

document/templates/document/category_update_form.html
{% extends "base.html" %}
{% block content %}

    <h3>Update document category</h3>
    <div class="brick">
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="vertical-center">
                <button type="submit" class="button green-button">Update document category</button>
            </div>
        </form>
    </div>

{% endblock %}

document/templates/document/document_confirm_delete.html
{% extends "base.html" %}
{% block content %}

    <h3>Delete document</h3>
    <div class="brick">
        <form method="post">
            {% csrf_token %}

            <p>Do you really want to delete the document <strong>#{{ document.company_document_id }}</strong>?</p>

            <div class="vertical-center">
                <button type="submit" class="button red-button">Delete document</button>
            </div>
        </form>
    </div>

{% endblock %}

document/templates/document/document_detail.html
{% extends "base.html" %}

{% load static %}
{% block head %}
    <script src="{% static 'js/show_history.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}

    <h3>Document details</h3>
    <div class="brick">

        <table class="striped-table striped-table-top-border">
            <colgroup>
                <col style="width: auto;">
                <col style="width: 100%;">
            </colgroup>
            <tr>
                <td>ID: </td>
                <td>#{{ document.company_document_id }}</td>
            </tr>
            <tr>
                <td>Title: </td>
                <td>{{ document.title }}</td>
            </tr>
            <tr>
                <td colspan="2"><strong>Product</strong></td>
            </tr>
            <tr>
                <td>Name: </td>
                <td>
                    {% for product in document.product.all %}
                        <span>{{ product.name }}</span><br>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td>Cash flow model: </td>
                <td>
                    {% for product in document.product.all %}
                        <span>{{ product.model }}</span><br>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td colspan="2"><strong>Document</strong></td>
            </tr>
            <tr>
                <td>Category of documents:</td>
                <td>{{ document.category }}</td>
            </tr>
            <tr>
                <td>Valid from:</td>
                <td>{{ document.validity_start|date:"Y-m-d" }}</td>
            </tr>
            <tr>
                <td>Filename:</td>
                <td>{{ document_filename }}</td>
            </tr>
            <tr>
                <td>Description:</td>
                <td>{{ document.description }}</td>
            </tr>
        </table>

        <span style="display: inline-block; margin: 24px 0 0 12px; color: #333; font-size: 0.8em;">
            Created at <strong>{{ document.created_at }}</strong> by <strong>{{ document.created_by }}</strong>.
        </span>

        <br>
        <div style="display: flex;">
            {% if user_is_contributor or user_is_admin %}
                {# Fake two buttons to center the middle button #}
                <span class="button gray-button" style="visibility: hidden;">Edit</span>
                <span class="button red-button" style="visibility: hidden;">Delete</span>
            {% endif %}

            <div style="flex-grow: 2;" class="vertical-center">
                <a href="{% url "download" document.company.name document.company_document_id %}" class="button green-button" target="_blank">Download document</a>
            </div>

            {% if user_is_contributor or user_is_admin %}
                <a href="{% url "edit_document" request.user.profile.company.name document.company_document_id %}" class="button gray-button">Edit</a>
                <a href="{% url "delete_document" request.user.profile.company.name document.company_document_id %}" class="button red-button">Delete</a>
            {% endif %}
        </div>

<!--        {% if history_set %}-->
<!--            <div id="show-history" class="vertical-center" style="margin: 24px 0 0 0; font-size: 0.75em;">-->
<!--                <strong>Show history of changes</strong>-->
<!--            </div>-->

<!--            <div id="history" style="display: none;">-->
<!--                <hr style="border: 1px dashed #999; margin: 24px 0 24px 0;">-->
<!--                <table class="striped-table" style="font-size: 0.75em;">-->
<!--                    <tr>-->
<!--                        <th>Element</th>-->
<!--                        <th>Before</th>-->
<!--                        <th>After</th>-->
<!--                        <th>User</th>-->
<!--                        <th>Date</th>-->
<!--                    </tr>-->
<!--                    {% for history in history_set %}-->
<!--                    <tr>-->
<!--                        <td>{{ history.element }}</td>-->
<!--                        <td>{{ history.changed_from }}</td>-->
<!--                        <td>{{ history.changed_to }}</td>-->
<!--                        <td>{{ history.changed_by }}</td>-->
<!--                        <td>{{ history.changed_at|date:"Y-m-d H:i" }}</td>-->
<!--                    </tr>-->
<!--                    {% endfor %}-->
<!--                </table>-->
<!--            </div>-->
<!--        {% endif %}-->
    </div>

{% endblock %}

document/templates/document/document_form.html
{% extends "base.html" %}
{% block content %}

    <h3>Add document</h3>
    <div class="brick">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="vertical-center">
                <button type="submit" class="button green-button">Add document</button>
            </div>
        </form>
    </div>

{% endblock %}

document/templates/document/document_update_form.html
{% extends "base.html" %}
{% block content %}

    <h3>Update document</h3>
    <div class="brick">
        <!-- <form method="post" enctype="multipart/form-data"> -->
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="vertical-center">
                <button type="submit" class="button green-button">Update document</button>
            </div>
        </form>
    </div>

{% endblock %}

document/templates/document/login.html
{%  extends "base.html" %}

{% block content %}
    <div style="margin: 0 auto; width: 50%;">
        <h3>Log in</h3>
        <div class="brick">
            {% if form.login.errors %}
                {% for err in form.login.errors %}
                    {{ err|escape }}
                {% endfor %}
            {% endif %}

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="vertical-center"><button type="submit">Log in</button></div>
                <br>
                No account yet? <a href="{% url "register" %}"><u>Register.</u></a>
            </form>
        </div>
    </div>
{% endblock %}

document/templates/document/manage.html
{% extends "base.html" %}
{% block content %}

    <h3>Manage insurance products</h3>
    <div class="brick" style="overflow: auto;">
        <table class="striped-table">
            <colgroup>
                <col style="width: auto;">
                <col style="width: auto;">
                <col style="width: 100%;">
                <col style="width: auto;">
                <col style="width: auto;">
            </colgroup>
            <tr>
                <th>No</th>
                <th>Cash flow model</th>
                <th>Name of insurance product</th>
                <th></th>
                <th></th>
            </tr>
            {% for product in products %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="/search/?product={{ product.company_product_id }}" class="link">{{ product.model }}</a></td>
                <td><a href="/search/?product={{ product.company_product_id }}" class="link">{{ product.name }}</a></td>
                {% if user_is_contributor or user_is_admin %}
                    <td>
                        <a href="{% url "edit_product" request.user.profile.company.name product.company_product_id %}" class="link">edit</a>
                    </td>
                    <td>
                        <a href="{% url "delete_product" request.user.profile.company.name product.company_product_id %}" class="link">delete</a>
                    </td>
                {% else %}
                    <td>
                        <span class="disabled link-disabled tooltip">edit
                            <span class="tooltip-text">Only contributors can edit products.</span>
                        </span>
                    </td>
                    <td>
                        <span class="disabled link-disabled tooltip">delete
                            <span class="tooltip-text">Only contributors can delete products.</span>
                        </span>
                    </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>

        <div class="vertical-center">
            {% if user_is_contributor or user_is_admin %}
                <a href="{% url "add_product" %}" class="button green-button">Add insurance product</a>
            {% else %}
                <span class="button disabled-button tooltip">Add insurance product
                    <span class="tooltip-text">Only contributors can add products.</span>
                </span>
            {% endif %}
        </div>
    </div>


    <h3>Manage document categories</h3>

    <div class="brick">
        <table class="striped-table">
            <colgroup>
                <col style="width: auto;">
                <col style="width: 100%;">
                <col style="width: auto;">
                <col style="width: auto;">
            </colgroup>
            <tr>
                <th>No</th>
                <th>Name of document category</th>
                <th></th>
                <th></th>
            </tr>
            {% for category in categories %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="/search/?category={{ category.company_category_id }}" class="link">{{ category.name }}</a></td>
                {% if user_is_contributor or user_is_admin %}
                <td>
                    <a href="{% url "edit_category" request.user.profile.company.name category.company_category_id %}" class="link">edit</a>
                </td>
                <td>
                    <a href="{% url "delete_category" request.user.profile.company.name category.company_category_id %}" class="link">delete</a>
                </td>
                {% else %}
                <td>
                    <span class="disabled link-disabled tooltip">edit
                        <span class="tooltip-text">Only contributors can edit categories.</span>
                    </span>
                </td>
                <td>
                    <span class="disabled link-disabled tooltip">delete
                        <span class="tooltip-text">Only contributors can delete categories.</span>
                    </span>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>

        <div class="vertical-center">
            {% if user_is_contributor or user_is_admin %}
                <a href="{% url "add_category" %}" class="button green-button">Add document category</a>
            {% else %}
                <span class="button disabled-button tooltip">Add document category
                    <span class="tooltip-text">Only contributors can add categories.</span>
                </span>
            {% endif %}
        </div>
    </div>

{% endblock %}

document/templates/document/pagination.html
<div class="pagination vertical-center">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}"><div class="pagination-arrow">&laquo;</div></a>
    {% endif %}

    <div>Page {{ page.number }} of {{ page.paginator.num_pages }}</div>

    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}"><div class="pagination-arrow">&raquo;</div></a>
    {% endif %}
</div>

document/templates/document/product_form.html
{% extends "base.html" %}
{% block content %}

    <h3>Add insurance product</h3>
    <div class="brick">
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="vertical-center">
                <button type="submit" class="button green-button">Add insurance product</button>
            </div>
        </form>
    </div>

{% endblock %}